---
title: "Songs - Ballerz Bandeoke"
---

It's early days for Ballerz Bandeoke, we are aiming for up to 300 songs ! 

This smaller list will get us going on our journey. 


<ul>
<li><span style="color: yellow;">	Song Title	</span> <span style="color: white;">	Artist Name	</span></li>
<li><span style="color: yellow;">	What's Up?	</span> <span style="color: white;">	4 Non Blondes	</span></li>
<li><span style="color: yellow;">	In Da Club	</span> <span style="color: white;">	50 Cent	</span></li>
<li><span style="color: yellow;">	Take on Me	</span> <span style="color: white;">	a-ha	</span></li>
<li><span style="color: yellow;">	Dancing Queen	</span> <span style="color: white;">	ABBA	</span></li>
<li><span style="color: yellow;">	Mamma Mia	</span> <span style="color: white;">	ABBA	</span></li>
<li><span style="color: yellow;">	Highway to Hell	</span> <span style="color: white;">	AC/DC	</span></li>
<li><span style="color: yellow;">	Back in Black	</span> <span style="color: white;">	AC/DC	</span></li>
<li><span style="color: yellow;">	Rolling in the Deep	</span> <span style="color: white;">	Adele	</span></li>
<li><span style="color: yellow;">	I Don't Want to Miss a Thing	</span> <span style="color: white;">	Aerosmith	</span></li>
<li><span style="color: yellow;">	Because I Got High	</span> <span style="color: white;">	Afroman	</span></li>
<li><span style="color: yellow;">	School's Out	</span> <span style="color: white;">	Alice Cooper	</span></li>
<li><span style="color: yellow;">	Valerie	</span> <span style="color: white;">	Amy Winehouse & Mark Ronson	</span></li>
<li><span style="color: yellow;">	Complicated	</span> <span style="color: white;">	Avril Lavigne	</span></li>
<li><span style="color: yellow;">	Everybody (Backstreet's Back)	</span> <span style="color: white;">	Backstreet Boys	</span></li>
<li><span style="color: yellow;">	Stand by Me	</span> <span style="color: white;">	Ben E. King	</span></li>
<li><span style="color: yellow;">	Ain't No Sunshine	</span> <span style="color: white;">	Bill Withers	</span></li>
<li><span style="color: yellow;">	I Gotta Feeling	</span> <span style="color: white;">	Black Eyed Peas	</span></li>
<li><span style="color: yellow;">	Paranoid	</span> <span style="color: white;">	Black Sabbath	</span></li>
<li><span style="color: yellow;">	All the Small Things	</span> <span style="color: white;">	Blink-182	</span></li>
<li><span style="color: yellow;">	Livin' on a Prayer	</span> <span style="color: white;">	Bon Jovi	</span></li>
<li><span style="color: yellow;">	...Baby One More Time	</span> <span style="color: white;">	Britney Spears	</span></li>
<li><span style="color: yellow;">	Summer of '69	</span> <span style="color: white;">	Bryan Adams	</span></li>
<li><span style="color: yellow;">	When You're Gone	</span> <span style="color: white;">	Bryan Adams	</span></li>
<li><span style="color: yellow;">	Sunshine of Your Love	</span> <span style="color: white;">	Cream	</span></li>
<li><span style="color: yellow;">	Have You Ever Seen the Rain	</span> <span style="color: white;">	Creedence Clearwater Revival	</span></li>
<li><span style="color: yellow;">	Get Lucky	</span> <span style="color: white;">	Daft Punk & Pharrell Williams	</span></li>
<li><span style="color: yellow;">	Wagon Wheel	</span> <span style="color: white;">	Darius Rucker	</span></li>
<li><span style="color: yellow;">	Heroes	</span> <span style="color: white;">	David Bowie	</span></li>
<li><span style="color: yellow;">	Smoke on the Water	</span> <span style="color: white;">	Deep Purple	</span></li>
<li><span style="color: yellow;">	Personal Jesus	</span> <span style="color: white;">	Depeche Mode	</span></li>
<li><span style="color: yellow;">	Don't Start Now	</span> <span style="color: white;">	Dua Lipa	</span></li>
<li><span style="color: yellow;">	September	</span> <span style="color: white;">	Earth, Wind & Fire	</span></li>
<li><span style="color: yellow;">	Wonderful Tonight	</span> <span style="color: white;">	Eric Clapton	</span></li>
<li><span style="color: yellow;">	I Shot the Sheriff	</span> <span style="color: white;">	Eric Clapton	</span></li>
<li><span style="color: yellow;">	Go Your Own Way	</span> <span style="color: white;">	Fleetwood Mac	</span></li>
<li><span style="color: yellow;">	Learn to Fly	</span> <span style="color: white;">	Foo Fighters	</span></li>
<li><span style="color: yellow;">	Stacy's Mom	</span> <span style="color: white;">	Fountains of Wayne	</span></li>
<li><span style="color: yellow;">	All Right Now	</span> <span style="color: white;">	Free	</span></li>
<li><span style="color: yellow;">	Are You Gonna Be My Girl	</span> <span style="color: white;">	Jet	</span></li>
<li><span style="color: yellow;">	The Middle	</span> <span style="color: white;">	Jimmy Eat World	</span></li>
<li><span style="color: yellow;">	I Love Rock 'n' Roll	</span> <span style="color: white;">	Joan Jett	</span></li>
<li><span style="color: yellow;">	Folsom Prison Blues	</span> <span style="color: white;">	Johnny Cash	</span></li>
<li><span style="color: yellow;">	Don't Stop Believin' (Small Town Girl)	</span> <span style="color: white;">	Journey	</span></li>
<li><span style="color: yellow;">	Breaking The Law	</span> <span style="color: white;">	Judas Priest	</span></li>
<li><span style="color: yellow;">	Sexyback	</span> <span style="color: white;">	Justin Timberlake & Timbaland	</span></li>
<li><span style="color: yellow;">	Walking on Sunshine	</span> <span style="color: white;">	Katrina and the Waves	</span></li>
<li><span style="color: yellow;">	I Kissed a Girl	</span> <span style="color: white;">	Katy Perry	</span></li>
<li><span style="color: yellow;">	I Was Made For Lovin' You	</span> <span style="color: white;">	Kiss	</span></li>
<li><span style="color: yellow;">	Poker Face	</span> <span style="color: white;">	Lady Gaga	</span></li>
<li><span style="color: yellow;">	Sweet Home Alabama	</span> <span style="color: white;">	Lynyrd Skynyrd	</span></li>
<li><span style="color: yellow;">	A Design for Life	</span> <span style="color: white;">	Manic Street Preachers	</span></li>
<li><span style="color: yellow;">	Moves Like Jagger	</span> <span style="color: white;">	Maroon 5 & Christina Aguilera	</span></li>
<li><span style="color: yellow;">	All About That Bass	</span> <span style="color: white;">	Meghan Trainor	</span></li>
<li><span style="color: yellow;">	Ace of Spades	</span> <span style="color: white;">	Motörhead	</span></li>
<li><span style="color: yellow;">	Sweet Caroline	</span> <span style="color: white;">	Neil Diamond	</span></li>
<li><span style="color: yellow;">	Wonderwall	</span> <span style="color: white;">	Oasis	</span></li>
<li><span style="color: yellow;">	Happy	</span> <span style="color: white;">	Pharrell Williams	</span></li>
<li><span style="color: yellow;">	Another Brick in the Wall (Part 2)	</span> <span style="color: white;">	Pink Floyd	</span></li>
<li><span style="color: yellow;">	Everybody Hurts	</span> <span style="color: white;">	R.E.M.	</span></li>
<li><span style="color: yellow;">	Creep	</span> <span style="color: white;">	Radiohead	</span></li>
<li><span style="color: yellow;">	Californication	</span> <span style="color: white;">	Red Hot Chili Peppers	</span></li>
<li><span style="color: yellow;">	We Found Love	</span> <span style="color: white;">	Rihanna & Calvin Harris	</span></li>
<li><span style="color: yellow;">	If It Makes You Happy	</span> <span style="color: white;">	Sheryl Crow	</span></li>
<li><span style="color: yellow;">	All Star	</span> <span style="color: white;">	Smash Mouth	</span></li>
<li><span style="color: yellow;">	Born to Be Wild	</span> <span style="color: white;">	Steppenwolf	</span></li>
<li><span style="color: yellow;">	Dakota	</span> <span style="color: white;">	Stereophonics	</span></li>
<li><span style="color: yellow;">	Superstition	</span> <span style="color: white;">	Stevie Wonder	</span></li>
<li><span style="color: yellow;">	Shake It Off	</span> <span style="color: white;">	Taylor Swift	</span></li>
<li><span style="color: yellow;">	Tribute	</span> <span style="color: white;">	Tenacious D	</span></li>
<li><span style="color: yellow;">	Come Together	</span> <span style="color: white;">	The Beatles	</span></li>
<li><span style="color: yellow;">	Get Back	</span> <span style="color: white;">	The Beatles	</span></li>
<li><span style="color: yellow;">	Twist and Shout	</span> <span style="color: white;">	The Beatles	</span></li>
<li><span style="color: yellow;">	Mustang Sally	</span> <span style="color: white;">	The Commitments	</span></li>
<li><span style="color: yellow;">	Zombie	</span> <span style="color: white;">	The Cranberries	</span></li>
<li><span style="color: yellow;">	Friday I'm in Love	</span> <span style="color: white;">	The Cure	</span></li>
<li><span style="color: yellow;">	The Wild Rover	</span> <span style="color: white;">	The Dubliners	</span></li>
<li><span style="color: yellow;">	Time Warp	</span> <span style="color: white;">	The Rocky Horror Picture Show (film) (Richard O'Brien, Patricia Quinn & Little Nell)	</span></li>
<li><span style="color: yellow;">	Honky Tonk Women	</span> <span style="color: white;">	The Rolling Stones	</span></li>
<li><span style="color: yellow;">	Blinding Lights	</span> <span style="color: white;">	The Weeknd	</span></li>
<li><span style="color: yellow;">	Whiskey In The Jar	</span> <span style="color: white;">	Thin Lizzy	</span></li>
<li><span style="color: yellow;">	Africa	</span> <span style="color: white;">	Toto	</span></li>
<li><span style="color: yellow;">	Ice Ice Baby	</span> <span style="color: white;">	Vanilla Ice	</span></li>
<li><span style="color: yellow;">	Buddy Holly	</span> <span style="color: white;">	Weezer	</span></li>
<li><span style="color: yellow;">	Teenage Dirtbag	</span> <span style="color: white;">	Wheatus	</span></li>
<li><span style="color: yellow;">	Play That Funky Music	</span> <span style="color: white;">	Wild Cherry	</span></li>
<li><span style="color: yellow;">	On the Road Again	</span> <span style="color: white;">	Willie Nelson	</span></li>
<li><span style="color: yellow;">	Girls Just Want to Have Fun	</span> <span style="color: white;">	Cyndi Lauper	</span></li>
<li><span style="color: yellow;">	Love Shack (Album Version)	</span> <span style="color: white;">	The B-52's	</span></li>
<li><span style="color: yellow;">	Wannabe	</span> <span style="color: white;">	Spice Girls	</span></li>
<li><span style="color: yellow;">	Don't Look Back in Anger	</span> <span style="color: white;">	Oasis	</span></li>
<li><span style="color: yellow;">	Champagne Supernova	</span> <span style="color: white;">	Oasis	</span></li>
<li><span style="color: yellow;">	Angels	</span> <span style="color: white;">	Robbie Williams	</span></li>
<li><span style="color: yellow;">	Shut Up and Dance	</span> <span style="color: white;">	Walk The Moon	</span></li>
<li><span style="color: yellow;">	Since U Been Gone	</span> <span style="color: white;">	Kelly Clarkson	</span></li>
<li><span style="color: yellow;">	Sweet Dreams (Are Made of This)	</span> <span style="color: white;">	Eurythmics	</span></li>
<li><span style="color: yellow;">	Faith	</span> <span style="color: white;">	George Michael	</span></li>
<li><span style="color: yellow;">	(You Gotta) Fight for Your Right (To Party!)	</span> <span style="color: white;">	Beastie Boys	</span></li>
<li><span style="color: yellow;">	A Little Respect	</span> <span style="color: white;">	Erasure	</span></li>
</ul>


